### ISSUE TITLE
Weather info lost upon restart of Sage

### ISSUE THREAD

**Issue by WaynerSage** [jusjoken/gemstone2#13]
The weather info appears to get lost when the Sage service is restarted and units reset from C to F.

**Comment by jusjoken** [comment]
which weather provider as i am not seeing this

**Comment by WaynerSage** [comment]
I normally use Wunderground as I have it tied to my own personal weather station.  But this might be a Celsius issue - see this thread:

http://forums.sagetv.com/forums/showthread.php?t=61237&highlight=celsius

**Comment by jptheripper** [comment]
I have this issue also.  Set to weather underground, frequently gets set back to world weather

**Comment by jusjoken** [comment]
i will test , but is this on a client or just extender?

**Comment by jusjoken** [comment]
I fixed this.  Weather settings for units and Provider are now stored at the server level and will therefore be consistent across providers, clients, extenders, placeshifters. Change it on any of those and it should change them all (at least on the next restart)
