### ISSUE TITLE
Single Flow sorted by year, then name

### ISSUE THREAD

**Issue by jptheripper** [jusjoken/gemstone2#20]
MyMovies had a flow that we really liked, and I am trying to recreate in gemstone.  It was single long horizontal flow, with year seperators (in flow).  Within each year, were titles sorted alphabetically.  

Gemstone is close with the folder for years, but - They cant be sorted Descending.  Which is really frustrating.  

Is there anyway to either sort by year and then name in a single flow, or at the least sort groupings

**Comment by jusjoken** [comment]
Do you mean a vertical list flow rather than horizontal? And i cannot 
imagine a level in a flow not being sortable

**Comment by jptheripper** [comment]
In a horizontal wall flow, I group by year.  It shows an icon for each year, but it sorts ascending, but i cant seem to get it to sort descending (2016 first).

**Comment by jusjoken** [comment]
Go into your wall Flow and select Options

Change the View to Movies (I assume you wanted movies but could select
Vidoes or something else)

Go into View Options

Change Level 1 - Group by Year, Sort by Title, Sort Order Decending

Change Level 2 - Sort by Title, Sort Order Ascending

Should work - I just tested it.

BTW - I think a cool Flow Type for this type of View is the Inline Flow
with the settings above.

**Comment by jptheripper** [comment]
Thank you so much! It's perfect
