### ISSUE TITLE
error (-8) when trying to record from guide

### ISSUE THREAD

**Issue by tomahawk51** [jusjoken/gemstone2#21]
The following error is reproducibly (always) observed when attempting to watch any show from the Guide, when (at least) the following conditions are true:

- Number of tuners setup for Sage = 1 (HDPVR)
- The tuner is currently recording something (else)
- In the guide, the Play button is pressed
- (user must press "OK", which just puts user back in the Guide)

> There was an error playing <show>:
> ERROR (-8): User rejected conflict resolution options for playback
> <OK>

The workaround has been:
- press the Record button
- Select Record This Show
- Read: "The newly select recording <> conflicts with scheduled recordings. Please select an option: 
- Select: Record my new selection instead of <> [alternate is Do Nothing]

Impact:
-Pain for me to record things (livable)
-Impossible for guests (e.g. babysitter) to use Gemstone effectively

**Comment by tomahawk51** [comment]
I guess one option might just be a few more prompt options to enable over-riding the active recording.

**Comment by jusjoken** [comment]
This is fixed already in the next release

**Comment by tomahawk51** [comment]
Sending gratitude!
